### ISSUE TITLE
Create a document for the Go SIG

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#1146]
The Go SIG lost access to and possibly all history of their meeting notes document. A new document should be created which is owned by an OpenTelemetry or CNCF google account in order to prevent this issue in the future. All community and calendar links will need to be updated with the new document.

**Comment by MrAlias** [comment]
We are using [this](https://docs.google.com/document/d/1NDtS-ym1Gmf3ZgyL5n9Lt-AGmoK_HH9RbenPRiSj7Fk/edit?usp=sharing) as a work around. Please let me know what account I need to transfer ownership to if we would like to persist the temp doc. Otherwise, if a new doc is created I can copy over the contents at that point.

**Comment by MrAlias** [comment]
cc @MadVikingGod @Aneurysm9

**Comment by dyladan** [comment]
Updated calendar link

**Comment by dyladan** [comment]
It will be closed by the linked PR which updates the community README.md with the new link
