### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-operator for opentelemetrybot

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/community#1384]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-operator

### Requested changes

Fork:
* https://github.com/redhat-openshift-ecosystem/community-operators-prod
* https://github.com/k8s-operatorhub/community-operators

to https://github.com/opentelemetrybot account.

### Purpose

Automate releasing of bundle manifests of https://github.com/open-telemetry/opentelemetry-operator to the operator hub repositories. At the moment the release is done manually and we would like to fully automate it. 

WIP PR: https://github.com/open-telemetry/opentelemetry-operator/pull/1573
 
### Expected Duration

"permanently"

### Repository Maintainers

@open-telemetry/operator-maintainers

**Comment by trask** [comment]
hey @pavolloffay, sorry for the delay on this, these repos are created now:

* https://github.com/opentelemetrybot/community-operators-prod
* https://github.com/opentelemetrybot/community-operators

I'll send a community PR to update https://github.com/open-telemetry/community/blob/main/assets.md#opentelemetry-bot once I fix the @opentelemetrybot 2FA so that others in @open-telemetry/governance-committee can get into

**Comment by pavolloffay** [comment]
thanks @trask
