### ISSUE TITLE
Exporting failed. Will retry the request after interval: context deadline exceeded

### ISSUE THREAD

**Issue by garima13del** [open-telemetry/community#1393]
I am deploying open telemetry collector in my k8s cluster and trying to export metrics to elastic apm but getting this error.

> Exporting failed. Will retry the request after interval.  {"kind": "exporter", "name": "otlp", "error": "rpc error: code = DeadlineExceeded desc = context deadline exceeded", "interval": "6.409817186s"}#

Sometimes this works for one cluster and when deployed in another cluster with same endpoint, both starts failing. 
Not sure what is causing this.

**Comment by trask** [comment]
hi @garima13del! since this is related to the collector, i'd start in one of these repos:

* https://github.com/open-telemetry/opentelemetry-collector-contrib
* https://github.com/open-telemetry/opentelemetry-collector

or in the [#otel-collector](https://cloud-native.slack.com/archives/C01N6P7KR6W) slack channel
