### ISSUE TITLE
REQUEST: Access to OpenShift cluster for OpenTelemetry Demo testing

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/community#1396]
We have several outstanding issues for the OpenTelemetry Demo related to OpenShift installations. We need access to an OpenShift cluster to facilitate development and testing.

Can the GC help get us access to a free OpenShift cluster to test the OpenTelemetry demo on it? We would need kubectl and Helm access to the cluster.

**Comment by arminru** [comment]
Making it work on OpenShift might also be in the interest of Red Hat. Maybe one of our community members from Red Hat could help facilitate that?

cc @pavolloffay @frzifus @yuriolisa

**Comment by pavolloffay** [comment]
I would recommend trying CRC https://developers.redhat.com/products/openshift-local/overview. It's a virtualized OCP instance for local development.

**Comment by sipples** [comment]
I understand the LinuxONE Community Cloud offers free OpenShift clusters. They're available for an initial 30 days, but you can renew up to 3 times (up to 120 days total). (You should get e-mails reminding you.) And it can be non-expiring if an open source project leader/maintainer asks, as I understand it, but you have to contact the Community Cloud operators to make such arrangements. The registration page is available here:
https://linuxone.cloud.marist.edu/#/register?flag=OCP
There's a brief (and possibly dated, so "mark it to market") "Getting Started" tutorial here:
https://developer.ibm.com/tutorials/red-hat-openshift-container-platform-linuxone-community-cloud-web-server/

The last time I used the LinuxONE Community Cloud I filled out the registration form and then a few hours later I was all set up. (I think there's a human step involved, so it'll typically be a weekday business hours kind of thing on their end.) You should get an e-mail with your initial credentials and basic access instructions. I'm not sure what release of OpenShift they're providing at this moment, but it's probably not the absolute latest release. It's a whole small cluster that you get. Understandably it'll be resource limited, but it's real. You can also get a Linux VM if you want that. Just change the "OCP" in the registration URL above to "VM" if that's what you want.

The LinuxONE Community Cloud is operated by Marist College as a community service. There's no "service level agreement," as you might expect since there's no fee involved. No performance or availability guarantees. It's something they do primarily for their own teaching purposes, but they've graciously opened it up to the rest of the world. If you happen to need some computing-related education (or even a degree) then check out Marist, but that's optional.

**Comment by trask** [comment]
> I would recommend trying CRC https://developers.redhat.com/products/openshift-local/overview. It's a virtualized OCP instance for local development.

hey @puckpuck, let us know if this will work out for you, thx

**Comment by puckpuck** [comment]
I applied to get OpenTelemetry access to an OpenShift cluster through LinuxOne. Thanks @sipples for the tip.

I also have CRC running a local version of OpenShift on my Mac now for testing, though a cluster that doesn't run on my local system is still preferred.

Thanks all for the help and pointers.
