### ISSUE TITLE
REQUEST: User group maintenance: add @damemi to the Go auto-instrumentation approvers team

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/community#1409]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-go-instrumentation

### Requested changes

Please add @damemi to the @open-telemetry/go-instrumentation-approvers group.

### Purpose

Mike is a founding member of the SIG and has agreed to taking on an approver role for the project.

**Comment by damemi** [comment]
Thanks @MrAlias, I'm happy to take on an approver role. Really excited about this project :)

**Comment by trask** [comment]
@open-telemetry/technical-committee can you fix the @open-telemetry/go-instrumentation-approvers group so that the members of @open-telemetry/go-instrumentaiton-maintainers (<-- btw that typo is super confusing) can manage it themselves?

> Every member of `foo-maintainers` should be included explicitly in `foo-approvers`
  and `foo-triagers` with the "Maintainer" GitHub privileges. This allows
  repository maintainers to invite new approvers and triagers to the team.

https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#collaborators-and-teams

**Comment by reyang** [comment]
Let me do it.

**Comment by reyang** [comment]
So I've added @damemi to the go-instrumentation-approvers group, and also make @MrAlias (who is in the go-instrumentation-maintainers group) a Maintainer of that group.

![image](https://user-images.githubusercontent.com/17327289/229927957-707aecfb-af00-4664-b2bd-922aff30a2e8.png)

**Comment by reyang** [comment]
@MrAlias would you add other maintainers?

**Comment by MrAlias** [comment]
> @MrAlias would you add other maintainers?

Sure thing. Thanks :tada:
