### ISSUE TITLE
OpenTelemetry mission, vision, and values

### ISSUE THREAD

**Issue by herrmku** [open-telemetry/community#1453]
Hey all

I would love to implement logging, tracing and monitoring using a standard like OpenTelemetry. I think, it is a great idea, to define a standard.
However, from the documentation, it is really hard to get a clue of how OpenTelemetry is thought to be working. I think it is really very hard work to get a grip on the topic in the current state.

- What does an application really need to do?
- What exactly are the Collectors responsible for?
- How is a standard setup, maybe multiple standard scnearios?
- In the Demo/Example, we see a lot of microservices in a drawing but we do not see an example of a trace going through them or a sample of a monitoring result
- The names are very - let's put it like that - academic - e.g. a span - the descriptions are not that much helpful to find a quick access to the topic

In order to get that standard flying, it would be a great job, if you could make the documentation more understandable. Abstract descriptions fine, but followed by examples that complete the technical explanation.

Would be very helpful.

Best regards

Kai-Uwe

**Comment by svrnm** [comment]
hey @herrmku, thanks for your feedback on the documentation of OpenTelemetry.

trying to understand where your feedback is coming from, since you raised this ticket with https://github.com/open-telemetry/community and not with https://github.com/open-telemetry/opentelemetry.io, are you referring to the documentation provided by the [website](https://opentelemetry.io/) or the documentation provided by the the individual subprojects (e.g. the specification, language specific implementations, etc.)? 

If the latter is the case, I would ask you to give the opentelemetry.io website a look, it's more geared towards end-users whereas for example the language in the specification is academic/technical on purpose, have a look into the [concepts](https://opentelemetry.io/docs/concepts/), language individual getting started guides (e.g. [Java](https://opentelemetry.io/docs/instrumentation/java/getting-started/) or [Node.JS](https://opentelemetry.io/docs/instrumentation/js/getting-started/nodejs/), ...) which give you some instructions on what you really need to do.

If it is the case that you are already looking at the opentelemetry.io website, I assume that some of the content you have been looking for was not easy to find, so I am happy to hear some feedback on how you navigate our website and where you suspected certain content.

Thanks,
