### ISSUE TITLE
Assign samiura to ebpf-approvers

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/community#1460]
See https://github.com/open-telemetry/opentelemetry-ebpf/pull/171. @samiura was added as approver to the opentelemetry-ebpf project and needs to be added to the correct github team.

**Comment by trask** [comment]
@open-telemetry/technical-committee can you update the @open-telemetry/ebpf-approvers group so that the members of @open-telemetry/ebpf-maintainers can manage it themselves?

> Every member of `foo-maintainers` should be included explicitly in `foo-approvers`
  and `foo-triagers` with the "Maintainer" GitHub privileges. This allows
  repository maintainers to invite new approvers and triagers to the team.

https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#collaborators-and-teams

**Comment by arminru** [comment]
@samiura please follow the process laid out here so we can add you to the Github organization first:
https://github.com/open-telemetry/community/blob/main/community-membership.md#member

**Comment by arminru** [comment]
@trask I added @yonch, @bjandras and @jimwsplk (current @open-telemetry/ebpf-maintainers) to @open-telemetry/ebpf-approvers and gave them Maintain permissions there.

**Comment by arminru** [comment]
Invited as requested in #1473 and added to the team.
