### ISSUE TITLE
Requesting TC review for PHP Metrics API/SDK spec compliance

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/community#1536]
Requesting a compliance review from https://github.com/orgs/open-telemetry/teams/technical-committee prior to GA release. If there are questions you can ask myself or any of the other PHP maintainers (@brettmc or @pdelewski)

**Comment by reyang** [comment]
I'll take this.

**Comment by reyang** [comment]
I'm not good at PHP so I could have misunderstanding.

Metrics API:
* There is an extra `weaken` parameter in the asynchronous instruments, the parameter is not covered by the spec and there is no comment about it in the code.
    * https://github.com/open-telemetry/opentelemetry-php/blob/cc92a07eac5294055b0d477fb7e47d6480381505/src/API/Metrics/ObservableGaugeInterface.php#L15
    * https://github.com/open-telemetry/opentelemetry-php/blob/cc92a07eac5294055b0d477fb7e47d6480381505/src/API/Metrics/ObservableCounterInterface.php#L15
    * https://github.com/open-telemetry/opentelemetry-php/blob/cc92a07eac5294055b0d477fb7e47d6480381505/src/API/Metrics/ObservableUpDownCounterInterface.php#L15

**Comment by brettmc** [comment]
Weaken:
I'm confirming with the original author, but my understanding is that it's about garbage collection. PHP keeps track of object references, and an object is not GC'd until there are zero references. Since we need to reference observable callbacks for async metrics, we provide a way to use PHP's [weak reference](https://www.php.net/manual/en/class.weakreference.php) mechanism so that we don't block the original object from being destroyed and GC'd.
In https://github.com/open-telemetry/opentelemetry-php/pull/1078 I've updated phpdoc to mention this, and provide an example of how it works.

MetricReader.ForceFlush:
It looks like our implementation matches what that PR is proposing, should we just wait and watch? It also looks like we're doing what java does: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricReader.java#L54

MetricExporterInterface.temporality:
We copied Java: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricExporter.java#L37

Examplar:
We copied java, but I see that they've marked a lot of their examplar classes as internal and documented that they might be unstable. Should we do the same?

**Comment by brettmc** [comment]
@reyang I've converted your observations into issues in our tracker. Have you finished your review?

**Comment by brettmc** [comment]
All issues addressed. @reyang let us know if you're finished reviewing. Thanks.

**Comment by brettmc** [comment]
_Qui tacet consentit_ - I think we can close this, @bobstrecansky

**Comment by reyang** [comment]
> All issues addressed. @reyang let us know if you're finished reviewing. Thanks.

I've finished the reviewing, looks like we're good to go! 🍾
