### ISSUE TITLE
Need help adding custom runners for performance benchmarks

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#1662]
Part of the work to get performance benchmarks requires us to use self-hosted github runners. Adding these, now that we have the hardware, is [pretty easy](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners). We just need someone w/ admin access to the open-telemetry org to help.

Related to https://github.com/open-telemetry/community/issues/1617

**Comment by trask** [comment]
> We just need someone w/ admin access to the open-telemetry org to help.

this would be @open-telemetry/technical-committee

**Comment by cartersocha** [comment]
We also need a TC owner on the equinix compute account

**Comment by jpkrohling** [comment]
Who's the TC sponsor for the performance benchmark SIG?

**Comment by cartersocha** [comment]
Haven’t had a chance to find one yet. But would love suggestions or volunteers

**Comment by tylerbenson** [comment]
@arminru helped me with this.  I think this can be closed now.

**Comment by arminru** [comment]
For future reference, these are steps we followed to set up and enroll a new runner in our org:

1. create the machine in Equinix
2. ssh into the machine by using the IP shown in the Equinix console
   - if your personal ssh key was in your Equinix profile at the time of machine creation, it will be in `authorized_keys` already
   - otherwise you can generate a temporary root password to log in and append your ssh key manually to `authorized_keys`
5. create a new user to execute the runner instead of root: `adduser --disabled-password ghrunner`
6. `su ghrunner`
7. follow instructions from https://github.com/organizations/open-telemetry/settings/actions/runners/new?arch=x64&os=linux
8. the config wizard asks for a group name - add the runner to "[Benchmark Bare Metal Runners](https://github.com/organizations/open-telemetry/settings/actions/runner-groups/8)"
9. provide some name (e.g. `github-benchmark-runner-<n>`), no extra labels
10. `./run.sh` to run it once and check if it succeeds
11. `exit` to go back to the root user
12. `./svc.sh install ghrunner` to install the runner as a service
13. `./svc.sh start`
14. check the Github UI at https://github.com/organizations/open-telemetry/settings/actions/runner-groups/8 
    - --> the new runner should show up and report as "🟢 idle"
