### ISSUE TITLE
Community feedback: what else should the GC be doing?

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1972]
The OpenTelemetry Governance Committee (@open-telemetry/governance-committee) has been reflecting on its role within the OpenTelemetry project, making explicit some of the implicit assumptions we have had so far. During that exercise, we identified examples, such as project management, establishing an overall roadmap, and ensuring we have a healthy pool of contributors. Those clarifications were implemented as part of #1932.

We'd also like to hear from the OpenTelemetry community, including contributors, maintainers, users, and vendors, what they'd like to see the Governance Committee doing.

In your opinion, what should the Governance Committee be doing in addition to what we already have in our [charter](https://github.com/open-telemetry/community/blob/main/governance-charter.md)?

Leave your comments here until 31 March 2024. We'll evaluate the answers and provide feedback on the changes that we'll incorporate based on that.

**Comment by cartermp** [comment]
I'd like to see an effort to advance the project to graduated status. I think, now that the initial vision has been delivered, and OTel is starting to see broad adoption across the industry, it's time to graduate from incubation and signal to to the early and late majority markets that this is tech you can rely on.

**Comment by woody1872** [comment]
I think enforcing minimum documentation standards across all components in the ecosystem would be worth discussing. There is a lot of really great documentation already, but also some not-so-great examples. I do think we have a bit of inconsistency here, and a lot of "check the comments in the source code" type of problems.

As an end-user, or as someone advocating for the usage of OpenTelemetry, when you run in to the latter it can be really challenging. Great documentation is really critical for adoption and support. Consistently getting this right across the ecosystem of components I feel is very important.

**Comment by jiekun** [comment]
I feel that this may be too detailed, but I still want to mention it here. We already have a testbed and have covered some components, but evaluating resource usage is an important task for end users.

Many components still lack reference data. We have a large number of receivers, processors, connectors, and exporters—how many resources do they require? For example, how much CPU and memory are needed to add a few processors to the existing setup?

Typically, the evaluation needs to be based on the actual workload, and users inevitably have to perform performance tests. However, it is still possible to provide baseline data. For example, if 10k samples per second (sps) require 1 CPU and 1 GB of memory, then for my collector cluster with 600k sps, I can start with 60 CPUs and 60 GB of memory, and then make adjustments accordingly.

I hope someone (not necessarily from GC, as these are not directional issues for the whole project/community) can plan to improve the performance evaluation, at least for the collector, so that each component has reference performance data. In this way, users can make adjustments based on that foundation, rather than starting from scratch.

**Comment by jpkrohling** [comment]
I dropped the ball on this one. I'll bring this to a GC meeting in a few weeks to discuss the comments brought here.

**Comment by danielgblanco** [comment]
We're thinking of having a regular (possibly annual) contributor survey. Rather than single and static community feedback, should this be something we do on an ongoing basis?

**Comment by jpkrohling** [comment]
I'm closing this, as the results of this was brought to the GC meeting this week.
