### ISSUE TITLE
For autoinstrumentation SIGs members

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/community#200]
1. Do we want to use the same maintainers/approvers as for the language SIG?
1. If not should we create new teams?
1. Should maintainers/approvers from the language SIG be automatically considered as approvers for the autoinstrumentation SIG?

**Comment by bhs** [comment]
1. IMO yes... this was covered in one of the discussions or docs but apparently didn't make it into the OTEP.
2. IMO N/A :)
3. I think so, yes

All of this said, I also think there's a case to be made for "overlaying" auto-instr maintainers on top of the language SIG (i.e., a superset relationship).

**Comment by bogdandrutu** [comment]
So, we need to clarify the otep to suggest that the same group of people are responsible for the autoinstrumentation and the library.

**Comment by yurishkuro** [comment]
I think No, Yes, & No. 

Maintaining the SDK and maintaining instrumentation or auto-instrumentation are two different responsibilities. We can seed each group with the same people initially, but I think they should be separate.

I would prefer we strive for more autonomy, at individual repo level. If someone did a bunch of work on instrumentation but never touched the SDK, elevating that person to maintainer/approver for instrumentation would also give them broad permissions for the SDK.

**Comment by bogdandrutu** [comment]
I am ok with this approach as well. I would like to know and document the decision in the otep so that I can follow to setup the Java auto-instr repo.

**Comment by bhs** [comment]
I guess I'd just like to know that the SDK SIG is "keeping an eye on" the auto-instrumentation SIG for each language... not due to a "lack of good intentions", but just because it could be easy for the two to get out of alignment; and I can easily imagine the auto-instrumentation group wanting changes in the SDK.

One idea: make sure that ≥1 SDK maintainer is involved with the auto-instrumentation discussions. I think that would help to prevent misalignment or "unpleasant surprises."

@yurishkuro @bogdandrutu WDYT?

**Comment by yurishkuro** [comment]
sgtm

**Comment by bhs** [comment]
I think we can close this now (since that PR was merged ^^^). @bogdandrutu please reopen if you disagree.
