### ISSUE TITLE
Create GitHub admin team and populate it

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#2066]
Now that #2025 has been merged, our next step is to create a new intermediate team to act as GitHub org admins for `open-telemetry`. This team should consist of GC and TC members.

The GC members are:
- @austinlparker 
- @trask 

The TC members are:
- tbd
- tbd

The name of the team should be something descriptive (e.g., `open-telemetry/gh-admins`).

**Comment by austinlparker** [comment]
@open-telemetry/technical-committee any volunteers?

**Comment by yurishkuro** [comment]
Created

**Comment by yurishkuro** [comment]
not sure where to set admin permissions, do we need a custom role for that?

**Comment by yurishkuro** [comment]
I added a custom role with all possible permissions

<img width="1217" alt="image" src="https://github.com/open-telemetry/community/assets/3523016/c87e0c42-38e9-449e-841e-8801000de4a8">

**Comment by yurishkuro** [comment]
@austinlparker @trask you should receive invites, please try it out

**Comment by austinlparker** [comment]
Ok, so this org role doesn't seem to be equivalent to the org owner, which is kinda challenging. Maybe add myself and trask as org owners and we'll start from there?

**Comment by arminru** [comment]
As per the docs for [Github org memberships](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-membership-in-your-organization/inviting-users-to-join-your-organization), for example, one needs to be a Github organization owner indeed to fulfill that aspect of the updated GC charter.
@trask and @austinlparker I added you as such now.
I'll also remove the `gh-admin` custom role again since it's not of any use anymore, as the org ownership already includes all permissions.
