### ISSUE TITLE
REQUEST: Repository maintenance on sig-end-user

### ISSUE THREAD

**Issue by danielgblanco** [open-telemetry/community#2078]
### Affected Repository

https://github.com/open-telemetry/sig-end-user

### Requested changes

* Make `main` the default branch
* Enable standard branch protection rules on `main`

 
### Purpose

The repo was recently setup, and the `main` branch was not created (or protected). The `main` branch is created now, but due to another branch being pushed first (without knowledge that there was no `main` branch) it automatically got made the default branch
 
### Expected Duration

Permanently

### Repository Maintainers

- @open-telemetry/sig-end-user-maintainers

**Comment by tigrannajaryan** [comment]
@danielgblanco I switch the default to `main` and added branch protection. One thing I was not able to do is enabling EasyCLA protection, not sure why it is not appearing in the list of status checks. Perhaps it will when the first PR is created?

I also made you an Admin on the repo so that you can make further changes if needed. Let me know if you prefer to stay and Admin or would like me to remove the permissions when you are done with the setup.

**Comment by arminru** [comment]
> Perhaps it will when the first PR is created?

@tigrannajaryan Exactly. It will only run on the first PR after creating a repo or making it public.

**Comment by arminru** [comment]
Since https://github.com/open-telemetry/sig-end-user/pull/1 triggered it, I was able to add EasyCLA as required for both `main` and `**/**`.

Keeping this open until we know if it's necessary to keep an Admin role on the repo.

**Comment by danielgblanco** [comment]
Thanks both. If it's all setup I would like to be removed from admins, unless I can remove myseff

**Comment by arminru** [comment]
Sure! I just removed you so the repo is following the standard setup now.
