### ISSUE TITLE
REQUEST: Change visibility of End-User SIG project to public

### ISSUE THREAD

**Issue by danielgblanco** [open-telemetry/community#2141]
### Affected Project
https://github.com/orgs/open-telemetry/projects/90

### Requested changes

Could you please change the visibility of the project to public using https://github.com/orgs/open-telemetry/projects/90/settings? Currently end-users that see it get a 404
 
### Purpose

The end-user SIG would like its progress and current actions to be visible to the general public.
 
### Expected Duration

Permanent

### Repository Maintainers

@open-telemetry/sig-end-user-maintainers

**Comment by danielgblanco** [comment]
Alternatively, I see that the org settings don't allow project admins to change visibility of their projects. Should that be changed instead? As more SIGs (especially ephemeral SIGs for specific projects) rely on project boards to communicate progress to the community and to end-users, I think it'd be good to allow them to make their project public if they need to, without requiring a ticket like this one.

**Comment by arminru** [comment]
@danielgblanco I made it public.

**Comment by arminru** [comment]
@open-telemetry/technical-committee I also looked into @danielgblanco's suggestion and followed https://docs.github.com/en/organizations/managing-organization-settings/allowing-project-visibility-changes-in-your-organization to allow project admins to make their boards public. I was not aware that this setting existed, otherwise I think we would've turned that one on a long time ago already. Let me know if you have any objections or concerns.

![image](https://github.com/open-telemetry/community/assets/7052238/c335f499-cb87-4962-93f6-06e29c7f6889)
