### ISSUE TITLE
project onboarding: Contributor Experience SIG

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2190]
With https://github.com/open-telemetry/community/pull/2162 merge, the Contributor Experience SIG can be onboarded, here are the TODOs to get them started:

- [x] Create project board
- [x] SIG Slack Channel
- [x] Meeting Notes (Google Docs)
- [x] Add GC Liaison, Slack Channel, Google Doc to sigs.yml
- [x] Meeting Time + Calendar Setup
- [x] GitHub Teams
- [x] Repository (?)

@JamieDanielson @jpkrohling @mx-psi @theletterf @musingvirtual

**Comment by svrnm** [comment]
for the board: https://github.com/orgs/open-telemetry/projects/97 -- but I need someone to make it public

**Comment by svrnm** [comment]
https://docs.google.com/document/d/1CTQI0p3QF8JP8reV8z_ggcs8KE5YVPpQGvAQknw4qP0/edit#heading=h.1zpfcitsf3o6 -- created

**Comment by svrnm** [comment]
https://groups.google.com/a/opentelemetry.io/g/calendar-contributor-experience

**Comment by musingvirtual** [comment]
Picking up where @svrnm left off - benefits of covering the globe!

Slack channel is created: #otel-contribex

**Comment by musingvirtual** [comment]
Updated sigs.yml (@jpkrohling & @svrnm maybe you can review)

https://github.com/open-telemetry/community/pull/2193

**Comment by musingvirtual** [comment]
TODO: 

I can make a doodle poll or similar to decide an initial meeting time (as discussed in Slack, with intention to eventually move to two meeting times, but for now it will probably end up in the standard US/EU window)


BLOCKED: 

make a calendar group and create a meeting (hidden subtask of editing sigs.yml)

https://github.com/open-telemetry/community/blob/386c9ed267134bba49bdbfcbd9cfbf0c6973bb52/docs/how-to-handle-public-calendar.md is unhelpful on these points because it says "admin@opentelemetry.io needs to create the meeting" but doesn't say who has access to that and how to get their attention, and it also doesn't say how to create calendar groups.  Does anyone know how this works?

**Comment by svrnm** [comment]
thanks for picking this up, @musingvirtual !

I created the group already, me or @jpkrohling can send out the invite when we have find a time to meet. For finding that time window: a doodle is fine, we can also do a poll on slack, whatever works best. We can also start with a biweekly from the get-go if we find out that this is the tendency

**Comment by musingvirtual** [comment]
@svrnm thanks! Sorry, I missed that comment because it was just a link. okay then I think we're finished other than meeting time if when you created the board you also created the team & repository!

**Comment by svrnm** [comment]
All setup!
