### ISSUE TITLE
REQUEST: Create new Docker Hub repository: otel/opentelemetry-collector-builder

### ISSUE THREAD

**Issue by jackgopack4** [open-telemetry/community#2353]
As described in [opentelemetry-collector issue #5712](https://github.com/open-telemetry/opentelemetry-collector/issues/5712), there is a plan to release a docker image along with opentelemetry collector builder (ocb) binaries to allow easier, more reproducible builds of custom collectors using ocb.

This was discussed on the [Collector SIG call today, September 18](https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit#heading=h.rbf22rxu3mij) and the general consensus was that the best name would be as listed in the title, `otel/opentelemetry-collector-builder`

Please assist with creating the repository manually: [hub.docker.com/r/otel/opentelemetry-collector-builder](https://hub.docker.com/r/otel/opentelemetry-collector-builder). Thank you for your help.

**Comment by tigrannajaryan** [comment]
@open-telemetry/collector-maintainers please confirm.

**Comment by mx-psi** [comment]
We discussed this on the 2024-09-18 Collector SIG meeting where @andrzej-stencel @jpkrohling and I agreed that `otel/opentelemetry-collector-builder` was the preferred name for this. 

I was under the assumption that the contrib maintainers would be the right group to approve this since it's going to be released from opentelemetry-collector-releases which is maintained by contrib maintainers, but if not I would like to wait for at least another core maintainer to give their :+1:

**Comment by bogdandrutu** [comment]
+1 for the name.

**Comment by tigrannajaryan** [comment]
https://hub.docker.com/r/otel/opentelemetry-collector-builder created.

**Comment by jackgopack4** [comment]
Thank you!

**Comment by bmf-san** [comment]
@jackgopack4 @tigrannajaryan 
It seems that the repository has been created, but it still appears to be empty.
Do you have any plans to push images?

**Comment by mx-psi** [comment]
@bmf-san We are still working on it, feel free to follow along on PR open-telemetry/opentelemetry-collector-releases/pull/671
