### ISSUE TITLE
Access to edit Public OpenTelemetry calendar

### ISSUE THREAD

**Issue by trask** [open-telemetry/community#287]
Can I get access to edit the Public OpenTelemetry calendar? I need to update the Java auto-instrumentation meeting schedule. Thx!

**Comment by bhs** [comment]
@trask this is not useful, but I just validated that I *can't* do this, sorry :-/

**Comment by mtwo** [comment]
@trask what's your email address? I'll add you

The calendar inherits from the OpenCensus calendar, which I (foolishly) created with my corporate Google account rather than my personal GMail account, and thus won't let us give ownership permissions to non-google.com accounts. The only way to rectify this is to create a new calendar and migrate everyone to it :/

**Comment by trask** [comment]
trask.stalnaker@gmail.com, thx!

**Comment by trask** [comment]
Thx @mtwo, all set now 👍

**Comment by tylerbenson** [comment]
> won't let us give ownership permissions to non-google.com accounts

@mtwo that should be something we make plans to rectify at some point...
