### ISSUE TITLE
How much should someone instrument in-process?

### ISSUE THREAD

**Issue by 3tilley** [open-telemetry/community#339]
Apologies if this was asked in the wrong places or has an answer somewhere!

Tracing in the traditional sense was all about function calls and expensive computations within a process. In the new world of distributed systems, clearly intra-process communication is the most important thing to track, as it has the highest variance and fault rate; and in the documentation for opentelemetry this is the focus. But what about services with expensive compute calls? Is there any guidance as to whether instrumentation should be cheap enough to call near hot paths? I'd like to know where opentelemetry stops and where traditional profiling begins.

To make this example concrete, I have experience with services that takes some input data and run a time-consuming complex model on it. Should there be multiple spans showing the various stages of computation? It would be extremely useful to see this alongside the network traces, but of course it has the potential to overwhelm. For Python, is it expected that the ubiquitous Pandas would be OT-instrumented to better myself profile expensive calls?

**Comment by jpirelli** [comment]
Disclaimer: I am new to this thread, as a matter of fact, this is my first post
Credit: I am not new to observability

When we are looking at the minimum requirement for instrumentation, a few key things come into play.
1. What does success for this operation look like?
2. Can I delineate what specific software was operating on the payload when it had a failure (in our stack, unless there is a blocker, this is the minimum bar as this is critical to know when determining which DRI team to engage)
3. Transactional load, storage costs etc.

In short, there is no single answer. As the SME for the process,  you would have to determine which aspects are important to you and what granularity is required for you to debug an issue or do analysis for service improvement. 

Like you rightfully called out, trapping all of the intraservice calls are key. If you have bandwidth, storage or transactional loads, you may make some choices around depth of debug data. In our case, we would always choose time to detect as the most required metric around a live issue. From there, the maturity and thoroughness of the telemetry stack is a function of maturity decided by those factors as well as how reliable a process is. In other words, we instrument processes with more failures more since we spend more time working on them as a pain point.

Hope this helps, I am with you in not sure about where to ask the question!

**Comment by lizthegrey** [comment]
Please feel free to ask follow-ups in https://gitter.im/open-telemetry/getting-started

In general, it's helpful to be _able_ to create spans for each meaningful unit of work; however, if the overhead is too large, being able to feature flag off or sample the spans is required to achieve performance. See the Distributed Tracing book recently published by OTel contributors from Lightstep: http://shop.oreilly.com/product/0636920273233.do
