### ISSUE TITLE
Use Google groups for easier SIG membership control and self-service

### ISSUE THREAD

**Issue by markcartertm** [open-telemetry/community#351]
Currently the OpenTelemetry project uses groups.io rather than Google groups. google groups is more commonly used in other large OSS projects.
Groups.io is slow and causes email delays, have a poor search experience and most importantly is less accessible to screen reader users. Google groups will also make it easier for project members to have the OTEL meetings added to their calendar as if the google group is added to the meeting any new member will get the calendar invite.
Given OTEl is inclusive project and is expected to grow, I suggest switching the project mailing lists to use Google groups going forward.
We can have the old groups forward to the new group aliases and respond with an auto reply saying our groups have moved.
This is the right time to make the switch before the project becomes too big.
CNCF indicated that they are ok with us using Google groups.

**Comment by markcartertm** [comment]
@mtwo  @tigrannajaryan  @SergeyKanzhelev  can you please bring up in next governance board meeting?

**Comment by SergeyKanzhelev** [comment]
Let me try to summarize the request:

> Groups.io 
> - slow and causes email delays
> - have a poor search experience 
> - most importantly is less accessible to screen reader users

Agree on first two... It's actually quite annoying. What is "less accessible to screen reader users"?

> Given OTEl is inclusive project ...

Back in OpenCensus time, we used Google CLA. There were complains from people who didn't want to associate anything with the google accounts. Just bringing it as one of a drawback for google groups. Since k8s is using it - shouldn't be a big issue though.

> Google groups will also make it easier for project members to have the OTEL meetings added to their calendar as if the google group is added to the meeting any new member will get the calendar invite.

We do not have a mailing list for every SIG. Instead all maintainers are given the edit permission to the calendar and can add people to the invite list explicitly on request. Is the suggestion to create and manage groups for every SIG?

References:
- Mailing lists: https://github.com/open-telemetry/community#mailing-lists
- Managing calendar: https://github.com/open-telemetry/community/blob/master/docs/how-to-handle-public-calendar.md

> We can have the old groups forward to the new group aliases and respond with an auto reply saying our groups have moved. This is the right time to make the switch before the project becomes too big.

If the suggestion is to create new groups - one for every SIG - there is nothing to set up for forwarding. The only groups we have are global members and contributors. And specialized restricted membership groups. As this proposal suggests something new - we can always add it as we need it.

> CNCF indicated that they are ok with us using Google groups.

What's the google groups ownership model? Are there any special permissions or group management needs to be configured?

**Comment by caniszczyk** [comment]
I just want to re-iterate that CNCF lets projects choose your own infrastructure. The reason groups.io is available is things like Google Groups are banned in China. You can potentially go the route of GitHub Discussions which is a new feature of GitHub that can be enabled, see this as an example https://github.com/zeit/next.js/discussions

**Comment by lizthegrey** [comment]
I hate groups.io as well :/ but including people in China also is valuable...

**Comment by mtwo** [comment]
@markcartertm which is the bigger challenge: group calendar invites or actual email discussions on groups.io? To be clear, I think that it handles both poorly, as do most members of the GC based off of this morning's discussion.

I ask because effectively all of the project's discussions take place on GitHub and Gitter, rather than on the mailing lists, and I don't think that switching mailing list providers will result in conversations moving from GitHub and Gitter back to email. However, I do think that we need a better solution for calendar invite lists and that Google Groups handles this better.

Perhaps we can create a Google Group specifically for calendar invites? **@markcartertm, would this solve your main concern?**

The GitHub discussions feature that @caniszczyk linked to also looks like a good way to host community questions, though we'll still want email lists for people to get in touch with groups like the TC and GC.

**Comment by mtwo** [comment]
I've created a Google group for people who want calendar invites sent directly to them (rather than adding an additional calendar to GMail / Outlook): https://groups.google.com/forum/#!forum/opentelemetry-calendar

**Comment by alolita** [comment]
I tried but don't seem to have access.

**Comment by mtwo** [comment]
Changed a setting, can you try again?

**Comment by trask** [comment]
closing as groups.io is no longer used
