### ISSUE TITLE
What are the PR MERGE requirements?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/community#41]
* For example get at least N approvals?
* Only maintainer can merge after N approvals?

**Comment by SergeyKanzhelev** [comment]
I'd suggest that 1 approval from Approver or Maintainer should be enough for language-specific decision. It may be different for the specification repo where we want to get to consensus on every issue. So perhaps everybody has to sign off. Or at least 3 people

**Comment by tedsuo** [comment]
BTW, this is related to the backlog proposal: https://github.com/open-telemetry/community/pull/52

Consider not just who can merge PRs, but also:
* Who triages new issues?
* Who can close unresolved issues? Or otherwise reject proposals?

In this case, though: I recommend 2 approvals for interface changes, and 1 approval for SDK and other changes.
