### ISSUE TITLE
Syncing SIG meetings with Outlook

### ISSUE THREAD

**Issue by xukaren** [open-telemetry/community#521]
Hi, 

The current [iCalendar link](https://github.com/open-telemetry/community/blob/master/README.md#calendar) in the README.md seems to include only some (not all) of the meetings in the [public calendar](https://calendar.google.com/calendar/u/0/embed?src=google.com_b79e3e90j7bbsa2n2p5an5lf60@group.calendar.google.com).

My question is: is there currently a way to sync all the OTEL SIG Meetings in the [public calendar](https://calendar.google.com/calendar/u/0/embed?src=google.com_b79e3e90j7bbsa2n2p5an5lf60@group.calendar.google.com) to Outlook? Also since the iCalendar `.ics` file is a static file, is there a way to automatically be notified of changed meeting times?  

Thank you!

(cc: @alolita)

**Comment by arminru** [comment]
Hi @xukaren! The Google calendar ical feed should be updated on a regular basis and include all calendar entries.
If you [Subscribe to an Internet Calendar in Outlook](https://support.microsoft.com/en-us/office/import-or-subscribe-to-a-calendar-in-outlook-on-the-web-503ffaf6-7b86-44fe-8dd6-8099d95f38df) providing the URL rather than downloading and importing the `.ics` file one single time, your Outlook should also pick up updates. Depending on how often Google calendar updates the feed and Outlook checks for changes, it might be a couple of hours off, however.
If you add your email address to this Google group, you should get invites (and change/cancellation notices) for all events instantly: https://groups.google.com/g/opentelemetry-calendar
