### ISSUE TITLE
Personal Access Token request for cross repo github actions

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/community#551]
The Python SIG is looking to configure GitHub actions to run tests in the opentelemetry-python-contrib repo when changes are pushed to the opentelemetry-python repo. In order to provide a status check for each PR, we need a personal access token (PAT) which will be configured in the github action to report back the status to the core repo.

The token needs only the `public_repo` scope selected. @NathanielRN can provide more details.

The work to separate the core from contrib repo is tracked via this issue: https://github.com/open-telemetry/opentelemetry-python/issues/1233

**Comment by SergeyKanzhelev** [comment]
Never done it myself, but happy to generate one. Is there a link to documentation on how to do it? Would personal access token from one of the maintainer for both project work?

**Comment by codeboten** [comment]
Here's a link to the docs: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

In theory yes, a maintainer could do it, but it seemed to make more sense to me to have ownership at the open-telemetry org level. I can be convinced otherwise though.

**Comment by SergeyKanzhelev** [comment]
Since the token cannot be limited to specific repositories, org level tokens would have too much permissions. Maybe we can create and manage a test infra accounts for this purpose? @open-telemetry/technical-committee does anybody has experience with this?

**Comment by NathanielRN** [comment]
The only concern I have is that someone could make PRs to maliciously run endless workflows.

Since it would be a PAT on the OTel Org, it would have access to run workflows on all OTel Org repos.

Having a maintainer create the token limits the access to the repos that the Maintainer has write permissions to, but has the same problem that their repos could be susceptible to maliciously running workflows on push to the repo with the PAT in the repo secrets.

**Comment by NathanielRN** [comment]
@SergeyKanzhelev Something like that would be great. I think something like a GitHub App per-language would work as well. Then that app's permissions would only extend to the repos (e.g. Python-Core & Python-Contrib) it has permissions to.

I think the OTel Org can create Github Apps? I was able to create a GitHub App with my personal account.

**Comment by SergeyKanzhelev** [comment]
@NathanielRN can you follow up with the @open-telemetry/python-maintainers to check what exactly would work and i or somebody with admin permissions for the org will help to make it happen.

**Comment by NathanielRN** [comment]
@SergeyKanzhelev Sure. We know a PAT token would work so we thought an issue like this would be a good place to bring up the pros & cons and get opinions on it.

Although I have confidence a GitHub App would work, I would say it's a bit overkill for a very first pass at cross repo workflows like these?

Thoughts on getting a PAT for now, investigating infra accounts like you mentioned @open-telemetry/technical-committee might know something about, or thoughts on another solution would be the best way I see for finding out next steps.

**Comment by SergeyKanzhelev** [comment]
So do you need anything now or will go with one of maintainer's PAT?

Let's wait for more comments on this issue in case somebody has experience with the service accounts.

**Comment by anuraaga** [comment]
Sorry to flyby, but I'd agree with going with maintainer rather than someone with org-level permissions for the exact reasons here :) Having bot accounts (e.g., opentelemetry-bot-python@opentelemetry.io with associated GitHub, PIP, etc accounts) with specific repo permissions would be nice in the long run. In Java, we currently use maintainer's personal bintray tokens for artifact upload, but I've wanted a opentelemetry-bot-java@opentelemetry.io with password shared through lastpass or similar to reduce the chance of single point of failure.

**Comment by Oberon00** [comment]
@codeboten Is this still an issue? https://github.com/open-telemetry/opentelemetry-python/issues/1233 is closed.

**Comment by SergeyKanzhelev** [comment]
> I've wanted a [opentelemetry-bot-java@opentelemetry.io](mailto:opentelemetry-bot-java@opentelemetry.io) with password shared through lastpass or similar to reduce the chance of single point of failure.

We have service lists for .NET and Ruby: https://github.com/open-telemetry/community/blob/master/assets.md#communication-channels We haven't set up password manager, but it is a good idea if somebody wants to drive this. I believe CNCF can sponsor either LastPass or 1Password.

**Comment by codeboten** [comment]
@Oberon00 thanks for following up, you're correct that this is no longer needed. I will close this issue.

@SergeyKanzhelev did you want to follow up on the password manager in a separate issue?
