### ISSUE TITLE
Request for repository admin

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/community#560]
As a website maintainer, I need admin access to the repository in order to address issues with PR's (editing files inline, for example).

Repository: https://github.com/open-telemetry/opentelemetry.io

**Comment by arminru** [comment]
I have now granted the @open-telemetry/docs-maintainers team [Maintainer](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) permissions as defined in our [repository policy](https://github.com/open-telemetry/community/blob/master/docs/how-to-configure-new-repository.md#permissions). Can you verify if that fulfills your needs and otherwise explain what permissions you'd additionally need? Thanks.

**Comment by austinlparker** [comment]
This works, thanks!
