### ISSUE TITLE
Align repository maintainer/admin access

### ISSUE THREAD

**Issue by arminru** [open-telemetry/community#616]
Our repository guidelines at https://github.com/open-telemetry/community/blob/6a33400d608709c8a9de6ffaf1bbcc117f622692/docs/how-to-configure-new-repository.md say:

> 5. The team `foo-maintainers` has `Maintain` permissions for the repository.
> 6. ...
> 7. Some repositories may include more individuals with `Admin` permissions.
   Typically to help set up repository, CI, web hooks or other administrative work.

According to the guideline above, only some individuals, if any, should be made an Admin.
The status quo, however, is that some OTel repos assign their maintainers team the Admin role, whereas others only give them Maintain permissions. We should either switch all to Maintain (+ individual Admins, if needed) or update the guidelines to formally allow this.

See https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization for a description of the roles. Admin is required to change the default branch (#402), for example.

**Comment by SergeyKanzhelev** [comment]
The only concern is that more documentation, education, and enforcement may be needed in this case. Mainly because as a project we need to ensure that PRs are not merged without CLA signoff (intentionally and unintentionally) and various levels of access defined in membership documentation are respected. We also (as an OSS project) do not keep backups of code for the case of unintended repo deletion. We had a gitter room deleted once by accident which wasn't a great experience.

As we reply fast for the request for admin permissions, it may not be such a problem. But I too think that at least CI configuration (except CLA) must be in full control of maintainers. Maybe some tooling may help.
