### ISSUE TITLE
Maintainers track proposals for KubeCon NA 2021

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/community#780]
Please submit your proposals for a topic for the OpenTelemetry maintainers track session as a comment to this issue. We are seeking for engaging topics, inspiring use and contribute to OpenTelemetry. If the topic you want to talk about is small, we can combine a few smaller ideas together. Please note speakers names and whether you plan to travel or attend virtually. Timeline for submissions is tight, we hope to make decision by end of the next week.

Here are notes from the KubeCon:

> 35-minute session during [KubeCon + CloudNativeCon North America](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/), being held October 11-15, within the “Maintainer Track."
>
> We recommend your 35-minute session be a combination of an introduction and deep dive of a CNCF project/working group/TAG/User Group/Subproject. Recommended durations for each section are listed below, but these should be used as a guideline and can be flexible depending on the content of your talk.
> 
> - The Intro portion should include some slides and a demo to explain what your activity does and why people should care. (Recommended: 15-minutes)
> - The Deep Dive portion is for contributors, maintainers, and other attendees with some pre-existing familiarity with the activity. We recommend that this should be a working part focusing on technical discussions and debates, as opposed to just processes (e.g., should the API be changed, not what's the best time for monthly conference calls). (Recommended: 20-minutes)
>
> You may have a maximum of four speakers in your session. Each speaker will be provided free registration to the conference.

**Comment by tedsuo** [comment]
I suggest we cover how native instrumentation works, and how library authors can get involved in the instrumentation effort.

## "Embedding OpenTelemetry Instrumentation in Open Source Software"
If you write OSS software, you may have noticed that it can be surprisingly difficult to send logs and metrics to the users who run your software. OpenTelemetry is designed to solve this problem. OpenTelemetry allows shared software libraries, such as web frameworks and database clients, to instrument themselves natively while still giving their end users control over where and how the data is processed. 

OSS libraries do a lot of heavy lifting. By giving library authors control over runtime observability their library produces, rather than relying on third party instrumentation plugins, OSS can move beyond testing and begin to participate in other modern devops practices.

In this session, we will cover:
* Guidelines for instrumenting your library natively, using OpenTelemetry.
* Playbooks and other benefits from native instrumentation.
* Why standardizing telemetry data is helpful to end users.

We will also cover the current state of OpenTelemetry project:
* Which APIs are currently stable, and what long term support means.
* Which software domains (HTTP, SQL, Message Queues) have defined standards
* High level instrumentation constructs which combine tracing and metrics to simplify instrumentation.
* How to get involved with the native isntrumentation effort in OpenTelemetry.

**Comment by mtwo** [comment]
Alternatively, we could have a session describing the milestones that we've hit (traces earlier this year, metrics before Kubecon, etc.), so that Kubecon attendees who are not already familiar with the project can get caught up

**Comment by lmolkova** [comment]
I'd love to contribute to native library instrumentation (we've instrumented all azure SDKs with OTel and hope we can share our experience in a vendor-neutral way. The talk points mostly match @tedsuo's suggestion and I can bring real-world examples
- Benefits
- Guidelines
- Tricky parts and how to minimize them

Do we have other native instrumentation examples that can share their path? AWS?

**Comment by tedsuo** [comment]
Ok, we hit the deadline with CNCF so I submitted a talk based on this thread.
