### ISSUE TITLE
Request for a HTTP semantic conventions workgroup

### ISSUE THREAD

**Issue by denisivan0v** [open-telemetry/community#826]
[Semantic conventions for HTTP communications](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md) are available, but they remain in an experimental state. Related to the general semantic conventions workgroup requested in #803, we would like to request an additional workgroup that exclusively focuses on bringing semantic conventions for HTTP into a stable state.

We plan to discuss the following areas and the results in an OTEP:

- [Status codes and errors](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/trace/semantic_conventions/http.md#L48)
- [Url/components attribute sets](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/trace/semantic_conventions/http.md#L101)
- [Attributes, optional attributes](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/trace/semantic_conventions/http.md#L53)
- Request/Response body capture  
- Retries, redirects and hedging policies
- Context propagation
- WebSockets/Long-polling and streaming 

The proposed times for this workgroup are  Monday 8 AM PST, Tuesday 9 AM PST or Wednesday 9 AM PST.

For reference please see request for an Instrumentation SIG in #802, the request for a Semantic Convention workgroup in #803, and the request for Messaging Semantic Convention workgroup in #805.

cc: @productml-ai @alolita @lmolkova @pyohannes @tedsuo

**Comment by Oberon00** [comment]
> Retries, redirects and hedging policies

Note that retries when sending a message were also a topic in the messaging WG kick-off meeting (see https://github.com/open-telemetry/oteps/pull/173#discussion_r701762856). I think we should be careful when spinning up so many separate WGs that we do not come up with needlessly inconsistent solutions to very similar problems.

**Comment by lmolkova** [comment]
@Oberon00 
I don't think we'll end up with inconsistent solutions. Messaging spec should talk about messaging specifics and HTTP describes transport (which can be used for messaging among other things).
Concepts like redirects and some context propagation aspects (headers, chance of requests being reused) are HTTP-specific and need to be explained in HTTP spec.
If there are common parts, we can separate them to general spec, but they are worth discussing with different groups of experts.

Adding more context/proposals for the above items based on instrumenting Azure SDKs:

## Per current spec 4xx must result in span with Error status

404/409 error criteria depends on the app. 

**Proposal**: do not set error status for them. Also,  based on users feedback we get, users expect them to be customizable and we should have an idea how to let users customize them with extra scopes, span processors, etc

## Required attribute sets

> At least one of the following sets of attributes is required:
> * `http.url`
> * `http.scheme`, `http.host`, `http.target`
> * `http.scheme`, [`net.peer.name`](span-general.md), [`net.peer.port`](span-general.md), `http.target`
> * `http.scheme`, [`net.peer.ip`](span-general.md), [`net.peer.port`](span-general.md), `http.target`

As a result, users that write queries against raw data or Zipkin/Jaeger don't have consistent story across instrumentations and languages. e.g. they'd need to write queries like `select * where (getPath(http.url) == "/a/b" || getPath(http.target) == "/a/b")`

**Proposal**: define one required set of attributes, so library owners would have more clarity and UX will be consistent. The alternative is to add an SDK processor that would normalize attributes and populate one single set for all exporters. 

## Optional attributes

As a library owner, I don't understand the benefits of optional attributes: they create overhead, they don't seem to be generically useful (e.g. flavor), and are inconsistent across languages/libraries unless unified.

**Proposals**
- should instrumentation have 2 verbosity layers? Required-only and all attributes? 
- remove all optional
- make all required?

## Retries and redirects

Each try/redirect must have unique context to be traceable and to unambiguously ask for support from downstream service, which implies span per try.
Redirects: users may need observability into what server hop had an error/took too long. E.g. was 500/timeout from the final destination or a proxy?

Should we trace logical HTTP Client API span call: no, because it doubles HTTP instrumentation costs and provides benefits to <1% of HTTP calls that are ever retried. Also, we can't assume all users do retries through handler/interceptors and we'll provide inconsistent experience.

## Sampling:

- Need to mention between pre-sampling/post-sampling attributes (all that are required and available pre-sampling should be provided)
- To make it efficient for noop case, need a hint for instrumentation (e.g. `GlobalOTel.isEnabled()`) that SDK is present and configured before creating pre-sampling attributes

## Context propagation needs explanation

- Reusing instances of client HTTP requests between tries (it’s likely, so clean  up context before making a call)

### Not HTTP-specific, but needs to be explained/mentioned:
- Extracting/injecting context from the wire
- Always making spans current (in case of lower-level instrumentations) as Client HTTP spans could have children or extra events  (TLS/DNS)
- Server spans - pass it to client code

## WebSockets/Long-polling and streaming

Anything we can do better here? In many cases connection has app-lifetime, messages are independent - can we explain to users how to do manual tracing for individual messages? Do span events per message make sense at all? Need some real-life/expertize here

## Request/Response body (technically out-of-scope, but we should have an idea how to let users do it)

I heard a lot of user feedback that they want it, but
- We can’t read body in generic instrumentation
- We can let users collect them
- Attaching to server span is trivial
- Spec for client: we should have an approach to let users unambiguously associate body with http client span (e.g. outer manual span that wraps HTTP call and response reading and has event/log with body)
- Reading/writing body happens outside of HTP client API – how users can track it too?

**Comment by tigrannajaryan** [comment]
@iNikem I think you had some questions about HTTP semantic conventions, if I remember correctly, so you may be interested in this.

**Comment by SergeyKanzhelev** [comment]
Perhaps this can be solved as a set of PRs to specs repo instead of a WG? We got a feedback that the big number of WGs is harmful and hard to not-full-time contributors to follow and participate.

**Comment by pyohannes** [comment]
> Perhaps this can be solved as a set of PRs to specs repo instead of a WG? We got a feedback that the big number of WGs is harmful and hard to not-full-time contributors to follow and participate.

The reasons why we opted for introducing a WG for messaging (and HTTP):
1. It seemed we needed a focused group to work on a semantic conventions area, because a previous model with offline collaboration only resulted in a very slow progress.
2. We want (and need) SME inputs for the various semantic conventions, and distinct workgroups make it easy for SMEs to participate in discussions. A messaging architect wont sit through a 60 minute meeting to participate in a 15 minute discussions about messaging.
3. Those WGs should work towards bringing semantic conventions for a certain area to a stable state. Once that's achieved, the WG will be dissolved and we can discuss further changes in PRs and in meetings of the general instrumentation SIG.

However, I'm open to any other model that allows for focused in-person discussions. I'm not sure in how far the model is harmful, as all WGs are supposed to work on either OTEPs or spec PRs, which allow for offline collaboration and feedback without attending all meetings.

**Comment by lmolkova** [comment]
> Perhaps this can be solved as a set of PRs to specs repo instead of a WG? We got a feedback that the big number of WGs is harmful and hard to not-full-time contributors to follow and participate.

I think we need both: less controversial problems can be easily solved with PR and offline discussion. Probably we can get really far with that on HTTP. 
It would be nice to have group discussions for a path to stability and controversial things. Can we fit it into general semantic conventions meetings focused on certain issues and invite SMEs/architects there?

**Comment by denisivan0v** [comment]
> Can we fit it into general semantic conventions meetings focused on certain issues and invite SMEs/architects there?

I would suggest us to start with a separate WGs for now, so we can build groups of people around semantic conventions topics and agree on scopes. The way I see it, the next would be to resolve controversial problems within WGs, and once we reached that point it would be easier to address individual items and eventually bring the existing semantic conventions to an initial stable state.

Also, we still need to select time. Don't you mind to quickly vote by clicking on the corresponding reaction?

Monday 8 AM PST - 🎉
Tuesday 9 AM PST - ❤️
Wednesday 9 AM PST - 🚀

**Comment by tedsuo** [comment]
@denisivan0v can you make it to the Tuesday 4pm Pacific meeting?

I agree with @lmolkova's proposal. Reviewing the HTTP semconv OTEP, very little of it is actually HTTP-specific. Almost all of it relates to general issues we have with instrumentation. As a result, we are already discussing these issues at that meeting. We can use HTTP as the focus for those discussions, so that SMEs can participate.

**Comment by tedsuo** [comment]
Following up on this issue, for now we've decided to stick to two meetings per week:

* Tuesday 4pm Pacific
* Thursday 8am Pacific

We can add an additional meeting if these meetings are not sufficient. Also, please join the [#otel-instrumentation](https://cloud-native.slack.com/archives/C01QZFGMLQ7) slack channel to get alerted to new issues/PRs and have async discussions.
