### ISSUE TITLE
Should interns routinely be allowed to become members?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/community#844]
Our membership guidelines say:
>Members are continuously active contributors in the community. They can have issues and PRs assigned to them. Members are expected to participate in SIG or SIGs and remain active contributors to the community.

This seems to automatically disqualify most interns who typically spend a short amount of time on a project related to Otel and then their internship ends and they move on to something else. We do not have any mechanism to know when this happens and what likely happens is we have several past interns who are still registered as members but are inactive.

Should we have a rule to discourage interns (and their sponsoring companies) from applying for membership unless they commit to remain active for multiple months and also commit to terminate their membership when they stop working on Otel?

I have no strong opinion on this and I am fine to keep it as is and let interns be members if community prefers that. I am primarily seeking clarification rather than pushing for a change.

**Comment by markcartertm** [comment]
As a welcoming community, I think that there is a benefit in encouraging Interns to become project members as many of them make significant contributions.
In my experience, more than 50% of the interns get a full time offer and continue to contribute.

There is a good point here about removing no longer active members from project membership which I believe applies to everyone and not just interns.
Wondering if there is an automated way to detect project members that have not made any contributions for 90 days and auto remove them.
How is this handled in other projects?


On Sep 17, 2021, at 6:19 AM, Tigran Najaryan ***@***.***> wrote:


Our membership guidelines say:

Members are continuously active contributors in the community. They can have issues and PRs assigned to them. Members are expected to participate in SIG or SIGs and remain active contributors to the community.

This seems to automatically disqualify most interns who typically spend a short amount of time on a project related to Otel and then their internship ends and they move on to something else. We do not have any mechanism to know when this happens and what likely happens is we have several past interns who are still registered as members but are inactive.

Should we have a rule to discourage interns (and their sponsoring companies) from applying for membership unless they commit to remain active for multiple months and also commit to terminate their membership when they stop working on Otel?

I have no strong opinion on this and I am fine to keep it as is and let interns be members if community prefers that. I am primarily seeking clarification rather than pushing for a change.

**Comment by tigrannajaryan** [comment]
> In my experience, more than 50% of the interns get a full time offer and continue to contribute.

Good to hear. If it is a high percentage then this is probably a non-issue. I'll keep this open for now but if the community does not have similar concerns I will close it.

**Comment by SergeyKanzhelev** [comment]
@tigrannajaryan we may consider following the k8s approach: https://github.com/kubernetes/org/issues/2456

Having interns sponsored by approvers/maintainers from two different companies is a good entry level barrier and we never know if contributions will continue.

**Comment by tigrannajaryan** [comment]
> Having interns sponsored by approvers/maintainers from two different companies is a good entry level barrier and we never know if contributions will continue.

Sounds good. Closing the issue.

**Comment by alolita** [comment]
I'm disappointed to see this thread. My experience with intern engineers contributing to OpenTelemetry has been very positive with the contributions they've been making to the project as well as learning observability fundamentals from mentors with more than 75% of them returning to come back as full-time observability engineers. I believe good engineers can come from anywhere and OpenTelemetry is an inclusive and welcoming project. Let's make sure we continue to support all contributions and contributors including interns as members. 

Let's also define what "being active" means since I also see many full time engineers on open source projects who hold roles as triagers, code-approvers and maintainers and are inactive for months. Should "being active" on a project mean activity within a time period or based on other criteria e.g. number of contributions.
