### ISSUE TITLE
Add OpenTelemetry project roadmap 

### ISSUE THREAD

**Issue by alolita** [open-telemetry/community#871]
In my discussions with end-users and developers, a question I get asked often is about the OpenTelemetry roadmap, release plan and what's in development. It is tough for people who do not participate in the project day-to-day to get an at-a-glance update of the project's development roadmap and progress. I point them to opentelemetry.io/status and the feedback I've received is that they would like to see a version that is more "management friendly". Perhaps this could be represented by a Gantt chart or a bar chart.

I'd like to see a roadmap for the project posted on GitHub, perhaps in this Community repo, which gives me a At-a-Glance snapshot which is updated on a bi-weekly basis. 

Examples of other open source project release roadmaps are:

- https://nodejs.org/en/about/releases/
- https://www.openstack.org/software/roadmap/
- https://releases.openstack.org/wallaby/index.html?_ga=2.170195877.421964257.1634012849-1846510401.1634012849
- https://www.kernel.org/category/releases.html
- https://www.kubernetes.dev/resources/release/

The GC could help maintain this high-level at-a-glance roadmap. The TC could maintain a more detailed release plan.

Would love to hear what other contributors think. Please +1 if you think this would be useful.

**Comment by sharrmander** [comment]
I believe this status and roadmap topic is vitally important to make the project more accessible for early adopters.  

I chatted with an OTel end user today and asked them what their company would like to see with respect to an 'at-a-glance' roadmap. They immediately self-identified a gantt chart and wished to see a "one page view" that outlined every SDK and their current status w.r.t. tracing/metrics/logging implementation (using green if stable, red if not) and estimated timeline to declare stability. The end user uses multiple language SDKs and has been getting this information through CNCF slack channels.

From my perspective, I've also gravitated towards gantt-like charts in google sheets to represent similar information for my companies agents. I sketched out what I think would be helpful for OTel and was surprised to see it was more like a table with dates written instead of visualized gantt-style.
